environment:
  matrix:
    - PYTHON_MAJOR: 3
      PYTHON_MINOR: 7
    - PYTHON_MAJOR: 3
      PYTHON_MINOR: 8

cache:
  - .venv -> poetry.lock

install:
  # Remove UTF-8 from pytest.ini
  - findstr /V tput pytest.ini > pytest.ini.tmp
  - del pytest.ini
  - ren pytest.ini.tmp pytest.ini
  # Add Make and Python to the PATH
  - copy C:\MinGW\bin\mingw32-make.exe C:\MinGW\bin\make.exe
  - set PATH=%PATH%;C:\MinGW\bin
  - set PATH=C:\Python%PYTHON_MAJOR%%PYTHON_MINOR%;%PATH%
  - set PATH=C:\Python%PYTHON_MAJOR%%PYTHON_MINOR%\Scripts;%PATH%
  # Install system dependencies
  - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
  - set PATH=%USERPROFILE%\.poetry\bin;%PATH%
  - make doctor
  # Install project dependencies
  - make install

build: off

test_script:
  - make test-repeat
