dist: xenial

language: python
python:
  - "3.7"
  - "3.8-dev"

cache:
  pip: true
  directories:
    - ${VIRTUAL_ENV}

before_install:
  # https://github.com/sdispater/poetry/issues/613
  # - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  # - source $HOME/.poetry/env
  - pip install poetry
  - make doctor

install:
  - make install

script:
  - make test-repeat
  - make check
  - make mkdocs

after_success:
  - pip install coveralls
  - coveralls

notifications:
  email:
    on_success: never
    on_failure: never
