language: python
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

cache:
  pip: true
  directories:
    - ${VIRTUAL_ENV}

before_install:
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source $HOME/.poetry/env
  - make doctor

install:
  - make install

script:
  - make test-repeat
  - make check
  - make docs

after_success:
  - pip install coveralls
  - coveralls

notifications:
  email:
    on_success: never
    on_failure: never
