language: python
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

env:
  global:
    - PYTEST_OPTIONS="--count=5 --exitfirst"

cache:
  pip: true
  directories:
    - ${VIRTUAL_ENV}

before_install:
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python

install:
  - source $HOME/.poetry/env
  - make install

script:
  - make test
  - make check

notifications:
  email:
    on_success: never
    on_failure: never
