language: python
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

cache:
  pip: true
  directories:
    - ${VIRTUAL_ENV}

before_install:
  - pip install poetry

install:
  - make install

script:
  - make test
  - make check

notifications:
  email:
    on_success: never
    on_failure: never
