site_name: Datafiles
site_description: A file-based ORM for dataclasses.
site_author: Jace Browning

repo_url: https://github.com/jacebrowning/datafiles
edit_uri: https://github.com/jacebrowning/datafiles/edit/develop/docs

theme: readthedocs

markdown_extensions:
  - codehilite:
      linenums: True

nav:
- Home: index.md
- Options:
  - Setup: options/setup.md
  - Formats: options/formats.md
- Types:
  - Builtins: types/builtins.md
  - Extensions: types/extensions.md
  - Containers: types/containers.md
  - Custom Types: types/custom.md
- Utilities: utilities.md
- About:
  - Release Notes: about/changelog.md
  - Contributing: about/contributing.md
  - License: about/license.md
