site_name: Datafiles
site_description: A file-based ORM for dataclasses.
site_author: Jace Browning

repo_url: https://github.com/jacebrowning/datafiles
edit_uri: https://github.com/jacebrowning/datafiles/edit/develop/docs

theme: readthedocs

markdown_extensions:
  - codehilite:
      linenums: True

nav:
- Overview: index.md
- API:
  - Model: api/model.md
  - Manager: api/manager.md
  - Mapper: api/mapper.md
- Types:
  - Builtins: types/builtins.md
  - Extensions: types/extensions.md
  - Containers: types/containers.md
  - Custom Types: types/custom.md
- Formats: formats.md
- Utilities: utilities.md
- About:
  - Release Notes: about/changelog.md
  - Contributing: about/contributing.md
  - License: about/license.md
