site_name: Datafiles
site_description: A file-based ORM for dataclasses.
site_author: Jace Browning
repo_url: https://github.com/jacebrowning/datafiles

theme: readthedocs

nav:
- Home: index.md
- Advanced: advanced.md
- About:
  - Release Notes: about/changelog.md
  - Contributing: about/contributing.md
  - License: about/license.md
