site_name: Datafiles
site_description: A file-based ORM for dataclasses.
site_author: Jace Browning

repo_url: https://github.com/jacebrowning/datafiles
edit_uri: https://github.com/jacebrowning/datafiles/edit/main/docs

theme: readthedocs

markdown_extensions:
  - codehilite

nav:
  - Overview: index.md
  - API:
      - Model: api/model.md
      - Manager: api/manager.md
      - Mapper: api/mapper.md
  - Supported Types:
      - Builtins: types/builtins.md
      - Containers: types/containers.md
      - Extended Types: types/extensions.md
      - Custom Types: types/custom.md
  - File Formats: formats.md
  - Utilities: utilities.md
  - Logging: logging.md
  - Settings: settings.md
  - About:
      - Release Notes: about/changelog.md
      - Contributing: about/contributing.md
      - License: about/license.md
