[tool.poetry]
name = "form"
version = "0.1.0"
description = "File-based ORM for data classes."
authors = ["Jace Browning <jacebrowning@gmail.com>"]

[tool.poetry.dependencies]
python = "*"
decorator = "^4.3"
minilog = "^0.4.0"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
black = "^18.3-alpha.0"
pytest-describe = "^0.11.1"
pytest-expecter = "^1.2"
isort = "^4.3"
pytest-cov = "^2.5"
rerun = "^1.0"

