[tool.poetry]

name = "datafiles"
version = "0.0.0"
description = "File-based ORM for data classes."
authors = ["Jace Browning <jacebrowning@gmail.com>"]

[tool.poetry.dependencies]

python = "^3.7"

minilog = "^0.4.1b1"
classproperties = "^0.1.3"
"ruamel.yaml" = "^0.15.46"

[tool.poetry.dev-dependencies]

black = "^18.3-alpha.0"
isort = "^4.3"
pylint = "^2.0"
mypy = "*"

pytest = "^3.0"
pytest-cov = "*"
pytest-describe = "*"
pytest-mock = "*"
pytest-expecter = "*"
pytest-watch = "*"
