[tool.poetry]

name = "form"
version = "0.0.0"
description = "File-based ORM for data classes."
authors = ["Jace Browning <jacebrowning@gmail.com>"]

[tool.poetry.dependencies]

python = "^3.7"

decorator = "^4.3"
minilog = "^0.4.0"

[tool.poetry.dev-dependencies]

black = "^18.3-alpha.0"
isort = "^4.3"

pytest = "^3.0"
pytest-cov = "*"
pytest-describe = "*"
pytest-expecter = "*"
pytest-watch = "*"

rerun = "^1.0"

